#!/usr/local/bin/Rscript

suppressPackageStartupMessages({
  library(TransPhylo)
  library(ape)
  library(lattice)
  library(coda)
  library(GetoptLong)
})

#################################################
# Command-line arg parsing
#################################################

seed<-123123
genMean <- 5.2
genSD <- 1.72
end<-2019.2
nMCMC<-100000
thin<-1000
burn<-0.2
out<-"out"
thresh=0.9

GetoptLong(
  "tree=s", "Path to newick-formatted simulated time tree",
  "sim=s", "Path to RDS file generated by sim_transphylo.R",
  "end=f", "Simulation end date",
  "genMean=f", "Generation time distribution mean (days)",
  "genSD=f", "Generation time distribution stdev (days)",
  "nMCMC=i", "Total number of MCMC iterations",
  "thin=i", "Thinning interval for MCMC", 
  "burn=f", "Proportion of MCMC iterations to discard as burn-in",
  "out=s", "Output file prefix",
  "thresh=f", "Posterior probability threshold for outputting transmission pairs",
  "seed=i", "Random number seed"
)

#################################################
# Main
#################################################

set.seed(seed)

print("Reading inputs...")

simu <- readRDS(sim)
phy<-read.tree(file=tree)
ptree<-ptreeFromPhylo(phy,dateLastSample=dateLastSample(simu))

print("Inferring transmission tree...")
res<-inferTTree(ptree,
                w.mean=genMean/365,
                w.std=genSD/365,
                dateT=end,
                mcmcIterations=nMCMC,
                thinning=thin,
                optiStart=2, 
                updateNeg = TRUE,
                updateOff.r = TRUE,
                updatePi = TRUE,
                updateOff.p = FALSE)
print("Done!")
print(res)

# plot mcmc 
pdf(paste0(out,"_mcmcout.pdf"))
plot(res)
dev.off()

# calculate ess
mcmc<-convertToCoda(res)
ess<-effectiveSize(mcmc)
print("Calculating effective sample sizes (ESS):")
print(ess)

#get tree
med=medTTree(res, burnin=burn)
ttree=extractTTree(med)

#cons.ttree <- consTTree(res, burnin=burn)

# pairwise transmission matrix 
print("Generating pairwise transmission matrix...")
wiw <- computeMatWIW(res, burnin=burn)
pdf(paste0(out,"_levelplot.pdf"))
lattice::levelplot(wiw,xlab='',ylab='')
dev.off()

# write wiw
print("Extracting transmission pairs...")
to<-rownames(wiw)[which(wiw > thresh, arr.ind = TRUE)[, 1]]
from<-colnames(wiw)[which(wiw > thresh, arr.ind = TRUE)[, 2]]
pp<-wiw[wiw > thresh]
pairs <- data.frame("from"=from, "to"=to, "prob"=pp)
write.table(pairs,
            file=paste0(out, ".pairs"),
            col.names=TRUE,
            row.names=FALSE,
            sep="\t",
            quote=FALSE)

print("Outputting full results as RDS...")
saveRDS(res, paste0(out, "_transphylo_output.rds"))
saveRDS(wiw, paste0(out, "_transphylo_matrix.rds"))
print("Done!")
